

# [Req] // 11ms
# POST http://localhost/api/v2/insert/updatelog
# content-type: application/json

# {
#     "Host_ip": "1.1.1.1",
#     "Host_name": "dummy_name",
#     "Winver": "22H1",
#     "Buildver": "19044.2486",
#     "Result": 0
# }


# [Req] // 2ms
# GET http://localhost/api/v2/winver/19090


# [Req] // 2ms
GET http://localhost/api/v2/connpool/max/2
# GET http://localhost/api/v2/connpool/info