version: "3"

services:
  db:
    image: mariadb:10.9.4
    ports:
      - 3306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - db_data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: ./db/env
    environment:
      TZ: Asia/Seoul
    restart: always

  web:
    image: golang:1.19.4
    ports:
      - 80:9999
    volumes:
      - ./web:/go/src
    command: sleep infinity
    depends_on:
      - db

  nginx:
    container_name: file_server
    image: nginx:1.23.3
    ports:
      - 80:9999
      - 8080:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/content:/var/www
volumes:
  db_data: {}
